package PAQUETE_GUI;

import PAQUETE_DP.PedidoDP;
import PAQUETE_DP.EntregaDP;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class VentanaEntrega_crear extends javax.swing.JInternalFrame {

    private PedidoDP pedidoDP;
    private EntregaDP entregaDP;
    private boolean existeEntrega;

    public VentanaEntrega_crear() {
        pedidoDP = new PedidoDP();
        entregaDP = new EntregaDP();
        existeEntrega = false;
        initComponents();
        cargarComboBoxPedido();
        cargarTiposEntrega();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_entNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb_entTipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_entComentario = new javax.swing.JTextArea();
        btn_etnGuardar = new javax.swing.JButton();
        cb_entNumPedido = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear entrega");

        jLabel2.setText("Número de entrega:");

        tf_entNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_entNumeroFocusLost(evt);
            }
        });

        jLabel3.setText("Número de pedido:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Comentario:");

        ta_entComentario.setColumns(20);
        ta_entComentario.setLineWrap(true);
        ta_entComentario.setRows(5);
        jScrollPane1.setViewportView(ta_entComentario);

        btn_etnGuardar.setText("Guardar");
        btn_etnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_etnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(276, 276, 276)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_etnGuardar)
                    .addComponent(cb_entNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGap(27, 27, 27)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addComponent(tf_entNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addComponent(cb_entTipo, 0, 285, Short.MAX_VALUE))
                    .addContainerGap(107, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(cb_entNumPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addComponent(btn_etnGuardar)
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(tf_entNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(86, 86, 86)
                                    .addComponent(jLabel4)))
                            .addGap(24, 24, 24))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(cb_entTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(97, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_etnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_etnGuardarActionPerformed
        if (camposCompletos()) {
            if (existeEntrega) {
                JOptionPane.showMessageDialog(jPanel1, "La entrega ya existe");
            } else {
                if (guardarDatos()) {
                    JOptionPane.showMessageDialog(jPanel1, "¡Creación exitosa!");
                    limpiarCampos();
                } else {
                    JOptionPane.showMessageDialog(jPanel1, "Creación fallida");
                }
            }
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Datos incompletos");
        }
    }//GEN-LAST:event_btn_etnGuardarActionPerformed

    private void tf_entNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_entNumeroFocusLost
        entregaDP.setEntregaNumero(Integer.parseInt(tf_entNumero.getText()));
        if (entregaDP.verificarExisteDP()) {
            JOptionPane.showMessageDialog(jPanel1, "La entrega ya existe");
            existeEntrega = true;
        } else {
            existeEntrega = false;
        }
    }//GEN-LAST:event_tf_entNumeroFocusLost
    private void cargarComboBoxPedido() {
        ArrayList<PedidoDP> pedidos = new ArrayList<>();
        pedidos = pedidoDP.consultarTodosPedidosDP();
        for (int i = 0; i < pedidos.size(); i++) {
            cb_entNumPedido.addItem(String.valueOf(pedidos.get(i).getPedidoNumero()));
        }
    }

    public void cargarTiposEntrega() {
        try {
            Properties props = new Properties();
            props.load(new FileInputStream("src/PAQUETE_PRINCIPAL/parametros.properties"));
            String[] tipos = props.getProperty("tiposEntrega").split(",");

            for (String temp : tipos) {
                cb_entTipo.addItem(temp);
            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaEntrega_actualizar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean camposCompletos() {
        boolean valido = true;

        String entNumero = tf_entNumero.getText().trim();
        String pedNumero = cb_entNumPedido.getSelectedItem().toString();
        String entTipo = cb_entTipo.getSelectedItem().toString();
        String entComentario = ta_entComentario.getText().trim();

        if (entNumero.equals("") || pedNumero.equals("") || entTipo.equals("")
                || entComentario.equals("")) {
            valido = false;
        }
        return valido;
    }

    private boolean guardarDatos() {
        String entNumero = tf_entNumero.getText().trim();
        String pedNumero = cb_entNumPedido.getSelectedItem().toString();
        String entTipo = cb_entTipo.getSelectedItem().toString();
        String entComentario = ta_entComentario.getText().trim();

        entregaDP.setEntregaNumero(Integer.parseInt(entNumero));
        entregaDP.setPedidoNumero(Integer.parseInt(pedNumero));
        entregaDP.setTipo(entTipo);
        entregaDP.setComentario(entComentario);

        return entregaDP.insertarDP();
    }

    private void limpiarCampos() {
        tf_entNumero.setText("");
        ta_entComentario.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_etnGuardar;
    private javax.swing.JComboBox<String> cb_entNumPedido;
    private javax.swing.JComboBox<String> cb_entTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta_entComentario;
    private javax.swing.JTextField tf_entNumero;
    // End of variables declaration//GEN-END:variables
}
