package PAQUETE_GUI;

import PAQUETE_DP.PedidoDP;
import PAQUETE_DP.ProductoDP;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentanaPedido_eliminar extends javax.swing.JInternalFrame {

    PedidoDP pedidoDP;
    private boolean existePedido;
    ArrayList<ProductoDP> productos;

    public VentanaPedido_eliminar() {
        pedidoDP = new PedidoDP();
        existePedido = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_consPedido_todos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cb_elimPedido_parametro = new javax.swing.JComboBox<>();
        tf_elimPedido_argumento = new javax.swing.JTextField();
        btn_elimPedido_individual = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_eliminarPedido_producto = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar pedido");

        btn_consPedido_todos.setText("Eliminar");
        btn_consPedido_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consPedido_todosActionPerformed(evt);
            }
        });

        jLabel2.setText("Buscar por:");

        cb_elimPedido_parametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código" }));

        btn_elimPedido_individual.setText("Buscar");
        btn_elimPedido_individual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_elimPedido_individualActionPerformed(evt);
            }
        });

        tb_eliminarPedido_producto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código de producto", "Descripción", "Precio", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_eliminarPedido_producto);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_elimPedido_parametro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tf_elimPedido_argumento, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_elimPedido_individual))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(btn_consPedido_todos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_elimPedido_parametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_elimPedido_argumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_elimPedido_individual))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btn_consPedido_todos)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_elimPedido_individualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_elimPedido_individualActionPerformed
        int pedidoNumero = Integer.parseInt(tf_elimPedido_argumento.getText());
        pedidoDP.setPedidoNumero(pedidoNumero);
        if (pedidoDP.verificarExisteDP()) {
            cargarDetallePedido();
            existePedido = true;
        } else {
            existePedido = false;
            JOptionPane.showMessageDialog(jPanel1, "El pedido no existe");
        }
    }//GEN-LAST:event_btn_elimPedido_individualActionPerformed

    private void btn_consPedido_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consPedido_todosActionPerformed
        if (existePedido) {
            int confirmacion = JOptionPane.showConfirmDialog(jPanel1, "¿Estás seguro de eliminar el pedido?");
            if (confirmacion == 0) {
                if (pedidoDP.eliminarDP()) {
                    limpiarCampos();
                    JOptionPane.showMessageDialog(jPanel1, "¡Eliminación exitosa!");
                    existePedido = false;
                } else {
                    JOptionPane.showMessageDialog(jPanel1, "Eliminación fallida");
                }
            }
        } else {
            JOptionPane.showMessageDialog(jPanel1, "El pedido no existe");
        }
    }//GEN-LAST:event_btn_consPedido_todosActionPerformed
    public void cargarDetallePedido() {
        ArrayList<ProductoDP> pedidos = pedidoDP.consultarDetalleDP();
        DefaultTableModel model = (DefaultTableModel) tb_eliminarPedido_producto.getModel();
        model.setRowCount(0);

        for (ProductoDP temp : pedidos) {
            model.addRow(new Object[]{temp.getCodigo(), temp.getNombre(),
                temp.getPrecio(), pedidoDP.getClienteCedula()});
        }

    }

    private void limpiarCampos() {
        DefaultTableModel model = (DefaultTableModel) tb_eliminarPedido_producto.getModel();
        model.setRowCount(0);
        tf_elimPedido_argumento.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consPedido_todos;
    private javax.swing.JButton btn_elimPedido_individual;
    private javax.swing.JComboBox<String> cb_elimPedido_parametro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_eliminarPedido_producto;
    private javax.swing.JTextField tf_elimPedido_argumento;
    // End of variables declaration//GEN-END:variables
}
