package PAQUETE_GUI;

import PAQUETE_DP.EstablecimientoDP;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class VentanaEstablecimiento_actualizar extends javax.swing.JInternalFrame {

    // atributos
    EstablecimientoDP establecimientoDP;
    boolean existeEstablecimiento;

    // constructor
    public VentanaEstablecimiento_actualizar() {
        establecimientoDP = new EstablecimientoDP();
        existeEstablecimiento = false;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tf_actualEstab_nombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_actualEstab_telefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_actualEstab_callePrincipal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_actualEstab_calleSecundaria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_actualEstab_numDireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_actualEstab_tipo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cb_actualEstab_parametro = new javax.swing.JComboBox<>();
        tf_actualEstab_argumento = new javax.swing.JTextField();
        btn_actualEstab_individual = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tf_actualEstab_codigo = new javax.swing.JTextField();
        btn_actualEstab_guardar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Actualizar establecimiento");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Teléfono:");

        jLabel5.setText("Calle principal:");

        jLabel6.setText("Calle secundaria:");

        jLabel7.setText("Número  de dirección:");

        jLabel8.setText("Tipo:");

        jLabel1.setText("Buscar por:");

        cb_actualEstab_parametro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código" }));

        btn_actualEstab_individual.setText("Buscar");
        btn_actualEstab_individual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualEstab_individualActionPerformed(evt);
            }
        });

        jLabel2.setText("Código:");

        btn_actualEstab_guardar.setText("Guardar");
        btn_actualEstab_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualEstab_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cb_actualEstab_parametro, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(tf_actualEstab_argumento, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_actualEstab_individual)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_actualEstab_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                    .addComponent(tf_actualEstab_telefono, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_actualEstab_callePrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                    .addComponent(tf_actualEstab_calleSecundaria, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_actualEstab_numDireccion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                    .addComponent(tf_actualEstab_tipo, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                    .addComponent(tf_actualEstab_codigo)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(361, 361, 361)
                        .addComponent(btn_actualEstab_guardar)))
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_actualEstab_parametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_actualEstab_argumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_actualEstab_individual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_actualEstab_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_actualEstab_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tf_actualEstab_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(tf_actualEstab_callePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tf_actualEstab_calleSecundaria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(tf_actualEstab_numDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_actualEstab_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_actualEstab_guardar)
                .addGap(65, 65, 65))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_actualEstab_individualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualEstab_individualActionPerformed
        establecimientoDP.setCodigo(tf_actualEstab_argumento.getText());

        if (establecimientoDP.verificarExisteDP()) {
            establecimientoDP.consultarDP();
            cargarEstablecimiento();
        } else {
            JOptionPane.showMessageDialog(jPanel1, "El establecimiento no existe");
        }
    }//GEN-LAST:event_btn_actualEstab_individualActionPerformed

    private void btn_actualEstab_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualEstab_guardarActionPerformed
        if (camposCompletos()) {
            if (guardarDatos()) {
                JOptionPane.showMessageDialog(jPanel1, "¡Actualización exitosa!");
                limpiarCampos();
            } else {
                JOptionPane.showMessageDialog(jPanel1, "Actualización fallida");
            }
        } else {
            JOptionPane.showMessageDialog(jPanel1, "Datos incompletos");
        }
    }//GEN-LAST:event_btn_actualEstab_guardarActionPerformed

// metodos de la clase
    private void cargarEstablecimiento() {
        tf_actualEstab_codigo.setText(establecimientoDP.getCodigo());
        tf_actualEstab_nombre.setText(establecimientoDP.getNombre());
        tf_actualEstab_telefono.setText(establecimientoDP.getNumTelefono());
        tf_actualEstab_callePrincipal.setText(establecimientoDP.getCallePrincipal());
        tf_actualEstab_calleSecundaria.setText(establecimientoDP.getCalleSecundaria());
        tf_actualEstab_numDireccion.setText(establecimientoDP.getNumDireccion());
        tf_actualEstab_tipo.setText(establecimientoDP.getTipo());
    }

    private boolean camposCompletos() {
        boolean valido = true;

        String codigo = tf_actualEstab_codigo.getText().trim();
        String nombre = tf_actualEstab_nombre.getText().trim();
        String telefono = tf_actualEstab_telefono.getText().trim();
        String calleP = tf_actualEstab_callePrincipal.getText().trim();
        String calleS = tf_actualEstab_calleSecundaria.getText().trim();
        String numDir = tf_actualEstab_numDireccion.getText().trim();
        String tipo = tf_actualEstab_tipo.getText().trim();

        if (codigo.equals("") || nombre.equals("") || telefono.equals("")
                || calleP.equals("") || calleS.equals("") || numDir.equals("")
                || tipo.equals("")) {
            valido = false;
        }
        return valido;
    }

    private boolean guardarDatos() {
        String codigo = tf_actualEstab_codigo.getText().trim();
        String nombre = tf_actualEstab_nombre.getText().trim();
        String telefono = tf_actualEstab_telefono.getText().trim();
        String calleP = tf_actualEstab_callePrincipal.getText().trim();
        String calleS = tf_actualEstab_calleSecundaria.getText().trim();
        String numDir = tf_actualEstab_numDireccion.getText().trim();
        String tipo = tf_actualEstab_tipo.getText().trim();

        establecimientoDP.setCodigo(codigo);
        establecimientoDP.setNombre(nombre);
        establecimientoDP.setNumTelefono(telefono);
        establecimientoDP.setCallePrincipal(calleP);
        establecimientoDP.setCalleSecundaria(calleS);
        establecimientoDP.setNumDireccion(numDir);
        establecimientoDP.setTipo(tipo);

        return establecimientoDP.modificarDP();
    }

    private void limpiarCampos() {
        tf_actualEstab_codigo.setText("");
        tf_actualEstab_nombre.setText("");
        tf_actualEstab_telefono.setText("");
        tf_actualEstab_callePrincipal.setText("");
        tf_actualEstab_calleSecundaria.setText("");
        tf_actualEstab_numDireccion.setText("");
        tf_actualEstab_tipo.setText("");
        tf_actualEstab_argumento.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualEstab_guardar;
    private javax.swing.JButton btn_actualEstab_individual;
    private javax.swing.JComboBox<String> cb_actualEstab_parametro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_actualEstab_argumento;
    private javax.swing.JTextField tf_actualEstab_callePrincipal;
    private javax.swing.JTextField tf_actualEstab_calleSecundaria;
    private javax.swing.JTextField tf_actualEstab_codigo;
    private javax.swing.JTextField tf_actualEstab_nombre;
    private javax.swing.JTextField tf_actualEstab_numDireccion;
    private javax.swing.JTextField tf_actualEstab_telefono;
    private javax.swing.JTextField tf_actualEstab_tipo;
    // End of variables declaration//GEN-END:variables
}
